name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^7.2.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  formz: ^0.4.0
  user_repository:
    path: packages/user_repository

dependency_overrides: null

dev_dependencies:
  bloc_test: null
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0

flutter:
  uses-material-design: true
