name: flutter_shopping_cart
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  bloc: ^7.2.1
  bloc_test: ^8.2.0
  flutter_bloc: ^7.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0

dependency_overrides: null

flutter:
  uses-material-design: true
