name: flutter_graphql_jobs
description: A example of how to use a GraphQL client with bloc.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.0.0
  json_annotation: ^4.0.0

dependency_overrides: null

dev_dependencies:
  bloc: ^7.2.1
  build_runner: ^2.0.0
  flutter_bloc: ^7.3.1
  json_serializable: ^4.0.0

flutter:
  uses-material-design: true
