name: flutter_firestore_todos
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  todos_repository:
    path: todos_repository
  user_repository:
    path: user_repository

dependency_overrides: null

flutter:
  uses-material-design: true
dev_dependencies:
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
